# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
resources:
  - app.yaml
  - database.yaml
  - discord-bot.yaml
  - services.yaml
  - ingress.yaml

secretGenerator:
  - name: database
    envs:
      - database.env

configMapGenerator:
  - name: discord-bot-config
    envs:
      - discord.env
